### PR TITLE
Add CSS to correct font color in themes

### LINKED ISSUE #280: Remaining issue with white background
There are still a number of styling issues when switching between dark/white background. Generally seem to be when new widgets are created when it's white, not all elements (text/borders) are set to darker, e.g.

image

Switching white->dark->while generally fixes it...

### PR DESCRIPTION
**Pull request by sanjayankur31**
Fixes #280

### CODE REVIEW

**Comment by sanjayankur31** [comment]
The second part of this fix is here: https://github.com/openworm/org.geppetto.frontend/pull/904

**Comment by sanjayankur31** [comment]
Note, to test this PR, one needs to update `docker-osb/Dockerfile` to use my forks:

```diff
diff --git a/Dockerfile b/Dockerfile
index 4ce0884..eef1a62 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -32,7 +32,7 @@ USER virgo
 ENV BRANCH_BASE=development
 ENV BRANCH_DEFAULT=v0.4.1-alpha
 ENV BRANCH_ORG_GEPPETTO=$BRANCH_DEFAULT
-ENV BRANCH_ORG_GEPPETTO_FRONTEND=populationConnectivity
+ENV BRANCH_ORG_GEPPETTO_FRONTEND=white-theme-fix
 ENV BRANCH_ORG_GEPPETTO_CORE=livemix
 ENV BRANCH_ORG_GEPPETTO_MODEL=$BRANCH_DEFAULT
 ENV BRANCH_ORG_GEPPETTO_MODEL_SWC=$BRANCH_DEFAULT
@@ -40,7 +40,7 @@ ENV BRANCH_ORG_GEPPETTO_MODEL_NEUROML=pg_temp2
 ENV BRANCH_ORG_GEPPETTO_PERSISTENCE=$BRANCH_DEFAULT
 ENV BRANCH_ORG_GEPPETTO_SIMULATION=livemix
 ENV BRANCH_ORG_GEPPETTO_SIMULATOR_EXTERNAL=mattTmp
-ENV BRANCH_GEPPETTO_OSB=osbDevelopment
+ENV BRANCH_GEPPETTO_OSB=add-white-theme-css
 
 # Persistence Config
 RUN mkdir -p /home/virgo/geppetto/
@@ -55,10 +55,10 @@ echo cloning required modules: && \
 git clone https://github.com/openworm/org.geppetto.git -b $BRANCH_BASE && \
 cd org.geppetto && git checkout $BRANCH_ORG_GEPPETTO || true
 RUN cd /opt/geppetto && \
-git clone https://github.com/openworm/org.geppetto.frontend.git -b $BRANCH_BASE && \
+git clone https://github.com/sanjayankur31/org.geppetto.frontend.git -b $BRANCH_BASE && \
 cd org.geppetto.frontend && git checkout $BRANCH_ORG_GEPPETTO_FRONTEND || true 
 RUN cd /opt/geppetto && \
-git clone https://github.com/OpenSourceBrain/geppetto-osb.git -b $BRANCH_BASE && \
+git clone https://github.com/sanjayankur31/geppetto-osb.git -b $BRANCH_BASE &&  \
 cd geppetto-osb && git checkout $BRANCH_GEPPETTO_OSB || true 
 RUN cd /opt/geppetto && \
 git clone https://github.com/openworm/org.geppetto.core.git -b $BRANCH_BASE && \
```

**Comment by sanjayankur31** [comment]
Tweaked it a bit more. No changes needed in org.geppetto.frontend. The changes here are sufficient. To test:

```diff
diff --git a/Dockerfile b/Dockerfile
index 4ce0884..c9bdbab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -40,7 +40,7 @@ ENV BRANCH_ORG_GEPPETTO_MODEL_NEUROML=pg_temp2
 ENV BRANCH_ORG_GEPPETTO_PERSISTENCE=$BRANCH_DEFAULT
 ENV BRANCH_ORG_GEPPETTO_SIMULATION=livemix
 ENV BRANCH_ORG_GEPPETTO_SIMULATOR_EXTERNAL=mattTmp
-ENV BRANCH_GEPPETTO_OSB=osbDevelopment
+ENV BRANCH_GEPPETTO_OSB=add-white-theme-css
 
 # Persistence Config
 RUN mkdir -p /home/virgo/geppetto/
@@ -58,7 +58,7 @@ RUN cd /opt/geppetto && \
 git clone https://github.com/openworm/org.geppetto.frontend.git -b $BRANCH_BASE && \
 cd org.geppetto.frontend && git checkout $BRANCH_ORG_GEPPETTO_FRONTEND || true 
 RUN cd /opt/geppetto && \
-git clone https://github.com/OpenSourceBrain/geppetto-osb.git -b $BRANCH_BASE && \
+git clone https://github.com/sanjayankur31/geppetto-osb.git -b $BRANCH_BASE &&  \
 cd geppetto-osb && git checkout $BRANCH_GEPPETTO_OSB || true 
 RUN cd /opt/geppetto && \
 git clone https://github.com/openworm/org.geppetto.core.git -b $BRANCH_BASE && \
```

**Comment by sanjayankur31** [comment]
@zsinnema this one is also a cosmetic change: adds a bit of CSS to ensure that the colours in the graphs match the theme. Could you test it if you have a minute too please?

**Comment by pgleeson** [comment]
Looks good @sanjayankur31, text is working better, but the axes are still missing/white on new plots, e.g. L23 tutorial:

Screenshot 2020-05-22 at 11 55 35

**Comment by pgleeson** [comment]
@sanjayankur31 Also feel free to make a branch here for updates

**Comment by sanjayankur31** [comment]
Closing this to open a new PR using a branch in this repo instead of the fork.

**Pull request closed without merging**
